export const products = [
    {
      id: 1,
      name: 'Add To Cart',
      href: '#',
      imgURL: 'https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8M3x8bGFwdG9wfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60',
    //     imageAlt: "Front of men's Add To Cart in black.",
      price: 100,
      color: 'Black',
    },
    {
      id: 2,
      name: 'Add To Cart',
      href: '#',
      imgURL: 'https://tailwindui.com/img/ecommerce-images/product-page-01-related-product-01.jpg',
      //   imageAlt: "Front of men's Add To Cart in black.",
      price: 100,
      color: 'Black',
    },
    {
      id: 3,
      name: 'Add To Cart',
      href: '#',
      imgURL: 'https://tailwindui.com/img/ecommerce-images/product-page-01-related-product-01.jpg',
      //   imageAlt: "Front of men's Add To Cart in black.",
      price: 100,
      color: 'Black',
    },
    {
      id: 4,
      name: 'Add To Cart',
      href: '#',
      imgURL: 'https://tailwindui.com/img/ecommerce-images/product-page-01-related-product-01.jpg',
      //   imageAlt: "Front of men's Add To Cart in black.",
      price: 100,
      color: 'Black',
    },
    {
      id: 5,
      name: 'Add To Cart',
      href: '#',
      imgURL: 'https://tailwindui.com/img/ecommerce-images/product-page-01-related-product-01.jpg',
      //   imageAlt: "Front of men's Add To Cart in black.",
      price: 100,
      color: 'Black',
    },
    {
      id: 6,
      name: 'Add To Cart',
      href: '#',
      imgURL: 'https://tailwindui.com/img/ecommerce-images/product-page-01-related-product-01.jpg',
      //   imageAlt: "Front of men's Add To Cart in black.",
      price: 100,
      color: 'Black',
    },
    {
      id: 7,
      name: 'Add To Cart',
      href: '#',
      imgURL: 'https://tailwindui.com/img/ecommerce-images/product-page-01-related-product-01.jpg',
      //   imageAlt: "Front of men's Add To Cart in black.",
      price: 100,
      color: 'Black',
    },
    {
      id: 8,
      name: 'Add To Cart',
      href: '#',
      imgURL: 'https://tailwindui.com/img/ecommerce-images/product-page-01-related-product-01.jpg',
      //   imageAlt: "Front of men's Add To Cart in black.",
      price: 100,
      color: 'Black',
    },
    // More products...
  ]
